---
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
        web02:
          ansible_host: 10.0.1.11
    databases:
      hosts:
        db01:
          ansible_host: 10.0.2.10
    monitoring:
      hosts:
        mon01:
          ansible_host: 10.0.3.10
    bastion:
      hosts:
        bastion01:
          ansible_host: 10.0.0.5
