---
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 10.0.1.10
        web02:
          ansible_host: 10.0.1.11
    databases:
      hosts:
        db01:
          ansible_host: 10.0.2.10
    monitoring:
      hosts:
        mon01:
          ansible_host: 10.0.3.10
    bastion:
      hosts:
        bastion01:
          ansible_host: 10.0.0.5
    domain_controllers:
      hosts:
        dc01:
          ansible_host: 10.0.4.10
          ansible_connection: winrm
          ansible_winrm_transport: kerberos
          ansible_winrm_scheme: https
          ansible_winrm_server_cert_validation: validate
          ansible_port: 5986
        dc02:
          ansible_host: 10.0.4.11
          ansible_connection: winrm
          ansible_winrm_transport: kerberos
          ansible_winrm_scheme: https
          ansible_winrm_server_cert_validation: validate
          ansible_port: 5986
