---
dhcp_server_host: "{{ groups['domain_controllers'][0] }}"

dhcp_scopes:
  - name: "LAN Principal"
    subnet: "10.0.1.0"
    mask: "255.255.255.0"
    start: "10.0.1.100"
    end: "10.0.1.200"
    router: "10.0.1.1"
    lease_duration_days: 8
    dns_servers:
      - "10.0.4.10"
      - "10.0.4.11"
    domain_name: "{{ ad_domain_name }}"
    description: "Scope serveurs web et applicatifs"

dhcp_exclusions:
  - scope_subnet: "10.0.1.0"
    start: "10.0.1.1"
    end: "10.0.1.99"

dhcp_reservations: []
# Exemple :
# - name: "web01"
#   ip: "10.0.1.10"
#   mac: "00:50:56:AA:BB:CC"
#   scope_subnet: "10.0.1.0"
#   description: "Serveur web 01"

dhcp_failover_enabled: false
dhcp_failover_partner: ""
dhcp_failover_mode: "HotStandby"   # HotStandby ou LoadBalance
dhcp_failover_percentage: 50
