---
- name: Déploiement complet de l'infrastructure Linux
  hosts: all:!domain_controllers
  gather_facts: true
  roles:
    - common
    - anssi-hardening

- name: Déploiement Active Directory et DHCP
  hosts: domain_controllers
  gather_facts: true
  roles:
    - active-directory
    - dns-windows
    - dhcp-windows

- name: Déploiement serveurs web
  hosts: webservers
  roles:
    - nginx

- name: Déploiement bases de données
  hosts: databases
  roles:
    - postgresql

- name: Déploiement monitoring
  hosts: monitoring
  roles:
    - monitoring
